alert("Welcome!");
var username, age, height;
let a, b, c;
username = "Tom";
age = "37";
console.log("username до изменения:", username, age);
username = "Bob";
console.log("username после изменения:", username, age);
var firstname, lastname;
firstname = "Maxim";
lastname = "Ivanov";
console.log(firstname);
console.log(lastname);
let user = "Jerry";
let company = "Samsung";
let language = "JS";
console.log(user, company, language);
let isMarried = false;
let text = `Name: ${username}, Age: ${age}, Married: ${isMarried}.`;
console.log(text);